### PR TITLE
Suggest to set a max_size

### PR DESCRIPTION
**Pull request by 695215742**
I suggest you set a max_size for connection_pool, otherwise there will maintain a large pool ,then many connections are useless.

### CODE REVIEW

**Comment by luca3m** [comment]
Good idea to add a maxsize. But `connection` has already its [destructor](https://github.com/luca3m/redis3m/blob/master/src/connection.cpp#L31) to free the underlaying C pointer, so you don't need a `release` method, just discard the object.

**Comment by 695215742** [comment]
Yes, but if you don't delete that connection explicitly, it will still be there.
I mean, when you get it as a pointer ,and you return the pointer. But the pool is full, you have to delete the pointer.

**Comment by luca3m** [comment]
Why? `connection::ptr_t` is a `std::shared_ptr`, so if no instance of it exists anymore, the connection object will be deleted as well.

**Comment by 695215742** [comment]
Maybe I am wrong, but I think if we don't release the ptr_t explicitly, it will delete itself until the end of its scope. But the scope is depend on where the user get the connection. So, I think it will cause some trouble.

**Pull request closed without merging**
